name = "EarthExile"
author = "Mazzy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fc1cb0c64ce952c7b20af25ca15ea499213c2c404f81c1f16e4d71f927c6a9a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
