name = "Earth Exile"
author = "Mazzy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87d42439c5ecd2bb811d0e1597a907881062b8aeec27fa8c1978f48fa95c8f05"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
